version: 0.2
phases:
  pre_build:
    commands:
      - echo Starting build
      - docker -v
      - echo $HOME
      - echo $PWD
      - docker login registry.gitlab.com  -u kaashyapan -p UHs-mCz6zQbyYBPqhaa2

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t apigateway:latest .
      - docker tag apigateway:latest registry.gitlab.com/kaashyapan/apigateway:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push registry.gitlab.com/kaashyapan/apigateway:latest
      - echo Pushed the docker image
